return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"angular",
				"bash",
				"blade",
				"c",
				"c_sharp",
				"comment",
				"cpp",
				"css",
				"csv",
				"dockerfile",
				"editorconfig",
				"fish",
				"gitignore",
				"go",
				"goctl",
				"gomod",
				"gosum",
				"gotmpl",
				"graphql",
				"html",
				"htmldjango",
				"java",
				"javadoc",
				"javascript",
				"jsdoc",
				"json",
				"json5",
				"jsonc",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"nginx",
				"php",
				"phpdoc",
				"printf",
				"prisma",
				"properties",
				"python",
				"query",
				"regex",
				"requirements",
				"robots",
				"rust",
				"scss",
				"sql",
				"svelte",
				"templ",
				"tmux",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"vue",
				"xml",
				"yaml",
			},
			auto_install = true,
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },

			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<Enter>", -- set to `false` to disable one of the mappings
					node_incremental = "<Enter>",
					scope_incremental = false,
					node_decremental = "<Backspace>",
				},
			},
		})
	end,
}
